---
author: HerbVar Manual Authorship Team
title-block-style: plain
date: 11/01/2024
date-modified: last-modified
title: Herbvar Research & Publication Workflow
---

## Overview {#sec-workflow}

HerbVar relies heavily on version control with Git/Github to facilitate data validation and management [@goodmanTenSimpleRules2014; @kimImplementingGitHubActions2022; @yenniDevelopingModernData2019], promote collaboration [@bolandTenSimpleRules2017; @bragaNotJustProgrammers2023], and streamline data access, analysis, and archiving [@champieuxTenSimpleRules2023]. Below we describe the workflow for (a) collecting data for HerbVar and uploading it for integration with the global data set and (b) analyzing some or all of the global HerbVar data set and preparing a manuscript based on these analyses.  

## New analysis with Herbvar Datasets

1. Identify Questions & Submit for Review (see @sec-project_review) to ensure no overlap with ongoing projects  
2. Create a repository for harvesting, organizing, and analyzing the data to be used in the analyses using the [`new_analysis_and_paper_template`](https://github.com/HerbVar-Network/analysis_and_paper_template) (see @sec-data-analysis).
3. Write the manuscript following the HerbVar guidelines for authorship (@sec-authorship_process) and Checklist for Writing Manuscripts (@sec-publications). Note that the Data Analysis Template can also be used to write the manuscript in markdown using a template such as [`papaja`](https://github.com/crsh/papaja) or one of the [`rticles`](https://github.com/rstudio/rticles) templates. 


## Collecting new HerbVar Data

1. Review and Select Protocols (see @sec-protocols-overview). 
2. Collect Data.
3. Create a repository for cleaning the data using HerbVar's [`new_dataset_template`](https://github.com/HerbVar-Network/new_dataset_template) (see @sec-data-analysis).
4. Upload the clean version of the data using the [Herbvar Data Portal](https://herbvar.shinyapps.io/data_portal_actual/)(see @sec-uploading_data).
5. Write the manuscript following the HerbVar guidelines for authorship (@sec-authorship_process) and Checklist for Writing Manuscripts (@sec-publications). Note that the Data Analysis Template can also be used to write the manuscript in markdown using a template such as [`papaja`](https://github.com/crsh/papaja) or one of the [`rticles`](https://github.com/rstudio/rticles) templates. 


