# Proposing New Analyses and Papers

Our network is excited about researchers using HerbVar data for new analyses and publications. The Steering Committee will periodically open calls for proposals for new data analysis projects. People interested in analyzing HerbVar data for publication should read @sec-authorship_process for a detailed outline of how to propose a project.

In brief, the prospective author(s) look at the list of products already being worked on, submit a working title and abstract to the HerbVar Steering Committee, and receive feedback/approval. The proposed publication is then listed on the HerbVar site for other network members to see. Authors are encouraged, but not required, to invite additional network members to work with them as appropriate. See Authorship Guidelines for discussion of how and when to invite others. This process provides benefits such as access to unpublished data, information on potential overlap of the paper with other completed or ongoing analyses, advice about how to interpret the data, GitHub tools customized for analysis and publication of HerbVar data, and publicity for the publication through HerbVar channels. 

Working Groups typically have six months to initiate work and two years from proposal to manuscript submission (or equivalent for non-manuscript projects). If manuscripts do not progress within those time frames the Steering Committee may make the data available to others interested in working on those questions.


