# Guidelines for Site PIs

## Guidelines for Participation as a Site PI

Site PIs must adhere to the following guidelines:

- Be professionally-trained researchers with expertise in plant-herbivore interactions.
- Be inclusive, collegial, and collaborative in their interactions with other members of HerbVar.
- Have or obtain supplies necessary for conducting their own surveys. As a distributed network, HerbVar does not have funding for data collection.
- Contribute data gathered using a standard HerbVar protocol or a modified protocol approved by the Steering Committee (see HerbVar Protocols in HerbVar Manual).
- Contribute species-level data on each species they survey (species-level traits), as requested by the Steering Committee.
- Recognize the contributions of all individuals involved in collecting HerbVar data, even if that individual’s participation does not satisfy the criteria for authorship. 
- Site PI’s should provide names, positions, and institutional affiliations of individuals who substantially contribute to data collection with them (“additional participants” columns in HerbVar Coordination and Completed Surveys documents). These additional participants will be recognized via the HerbVar website and via a link in the acknowledgments of HerbVar publications; we encourage Site PIs to also recognize participation locally.

- Follow the HerbVar data sharing and usage agreement: HerbVar-DataSharingContract-D5.docx

- Ensure that your data are high quality. Check your data for errors before submitting them, and inform us immediately of any errors that you discover after submission. We identify and fix data errors to the extent possible as part of our data wrangling process. We understand that some errors are a normal part of data collection, but datasets that have an unreasonable number of errors will be rejected and not count towards authorship. We will not count errors against you if you contact us about them. Some  mistakes are expected; the most important thing is for Site PI’s to be alert for errors and to communicate openly about them when they happen. 
