---
author:
  - name: Danielle Salcido
    affiliations:
      - id: unr
      - name: University of Nevada, Reno
        city: Reno
        state: NV
  - name: Lee Dyer
    affiliations:
      - id: unr
      - name: University of Nevada, Reno
        city: Reno
        state: NV
  - name: Will Wetzel
    affiliations:
      - id: umt
      - name: University of Montana
        city: Missoula
        state: MT
title-block-style: plain
date: 11/01/2021
date-modified: last-modified

---

# Low Density/Abundance Plants {#sec-low_density}

## Overview

This protocol outlines three methods for surveying sites where the focal plant plant occurs at low density or low abundance. The Primary Protocol was designed to work for many plant species, growth forms, and contexts, but it requires sites with enough focal plants at a reasonably high density for efficient random sampling using our transect/sub-transect method. If the focal plants at your site are at very low density, then sampling them with our primary method will be very time-consuming due to the large distances between plants. If they are at low abundance, such that there are fewer than about ~90 plants in the site, then it does not make sense to draw a random sample of 30 plants + 30 neighbors from such a small population. If none of the methods below work well for your species and site, we encourage you to think of a comparable alternative. Feel free to get in touch if you have questions. Regardless of what you decide, please make sure to carefully document your methods.

**_We provide three separate protocols for surveying sites with low density and/or abundance of focal plants:_**

1. Comprehensive Patch Census. 
2. Walking Transect.  
3. Comprehensive Census of Subset.

## Option 1: Comprehensive Patch Census

The best method, when feasible, is to census all of the individuals in a patch. This will work when there is a well-defined patch with a reasonable number of plants (e.g., < ~90). If this is possible, it is better in many ways than the Primary Protocol because it describes the whole distribution of herbivory at the site—there’s no risk of missing the tails of the distribution if every plant has been included! Also, depending on the context, this could be faster than our Primary Protocol because setting up transects and quadrats to randomly sample plants is time consuming. So comprehensively examining all of a patch’s 90 plants, for example, might be faster than randomly sampling 60 plants (30 focal plants and their 30 neighbors) from a larger population. For this method, we stress that you should strive to survey every plant.

### **Record spatial information via one of two methods**

**Option A. Record GPS position of each plant.** If you do this, you will not need to record nearest neighbor information because we can reconstruct it (and more!) easily from the geographic coordinates. This of course means that you will need a GPS sensitive enough to differentiate the locations of your plants. If your plants are on average more than 2-3 m apart, then almost any modern GPS will be precise enough. If, however, your plants average less than ~1 m apart, then you would need a very precise GPS to describe the relative locations accurately. If you don’t have such a precise GPS (or if you don’t like how slow a precise GPS can be), we recommend the second method.

**Option B: Relative spatial coordinates:** You can measure the relative coordinates of your plants using two tape measures or a tape measure and a meter stick. This sounds similar to the primary protocol but it’s much quicker because you’re not using the tapes to select plants, just to record their locations.

1. Lay a tape measure through your patch. For each plant, record spatial coordinates as how far along the tape measure and how far from the tape measure. You can situate the tape either along the edge of the patch or through the middle of the patch.

2. If your tape measure is through the middle of the patch, remember to record the distance left of the tape as negative and right of the tape as positive. The start of your tape will have the coordinate (0,0).

3. After recording this information, follow the Primary Protocol as closely as possible

### **Other useful information**

Record `popDiameter1` and `popDiameter2` as the approximate extents of your patch/census area

For focal plant percent cover (`focalPlantCover`) and non-focal plant percent cover (`otherPlantCover`), please follow the Primary Protocol methods for estimating population density and calculating a quadrat radius size, if feasible. You can then center a quadrat on each focal plant in the census to define an area around each focal plant for recording focal and non-focal percent cover, as well as the number of focal plants in quadrat (`numPlantsinQuad`).

In comprehensive surveys the ~60 plants will all be focal plants and there is no random selection; hence the nearest neighbors (all the ".1" plant IDs in datasheet template) become focal plants. As described above, a quadrat is centered around each plant and the three quadrat-level variables (`focalPlantCover`, `otherPlantCover`, and `numPlantsinQuad`) are recorded for each plant. The nearest neighbor distance (`NNdist`) is still recorded, but since that neighbor is treated as a focal plant, please record the unique plantID of that nearest neighbor as well (e.g. add `NNplantID` column as needed in datasheet).

If you cannot estimate population density (e.g., because your species is too sparse), then please pick an arbitrary quadrat radius. You can use that to define an area around each focal plant in your census for estimating percent cover variables. A 1-m radius might be a good choice for many plants, but go bigger for bigger plants. Remember to record your choice!

## Option 2: Walking Transect

Another alternative if you have widely dispersed plants that do not form a well-defined patch (or the patch is too large for a comprehensive search) is a walking transect. 

1. Randomly pick distances (e.g., paces) along a transect and from a transect.

2. Pace out the distance along the transect, then turn orthogonally to pace out the distance from the transect.

3. Survey the closest plant within some reasonable distance (if no plant is reasonably close, then go back to transect and keep going).

4. Repeat until you have 30 plants and 30 neighbors.

This is similar to the Primary Protocol except pacing (rather than measuring with a tape) can make large areas more feasible to survey. Consider recording spatial coordinates for each plant, especially if plants are far from your randomly identified points. And try to survey neighbors for each plant.

## Option 3: Comprehensive Census of Subset

This method is similar to the comprehensive census of a patch (#1 above), but it applies when there is no well-defined patch and individuals are widely dispersed over a large area. **_There are two ways to do this, but for both of these methods record spatial coordinates for each plant as described in Option #1 above._**  

**Option A - Comprehensive survey of all plants along a transect: **With this method, you are doing a comprehensive survey of a linear subset of the whole population. 

Start by randomly picking a transect starting point and direction. Walk the transect and survey every plant that crosses your path *or* every plant within a reasonable distance of your path (e.g., 2 m). Keep going until you get at least 60 plants.  
    
**Option B: Comprehensive survey radiating out from a random starting point within a population.** With this method, you are doing a comprehensive survey of a roughly circular (or blobby) area within the whole population. 

Explore outwards from your random starting point, surveying every plant you encounter until you get to at least 60 plants. _Note that we do not recommend doing this unless your plants truly are all widely dispersed._ If your plants are close together there could be high spatial autocorrelation such that you fail to capture the range of herbivory levels in the population. Of course, this is always a risk; it’s just especially acute when the sampling extent is an arbitrary area rather than a biologically significant “patch''.
 