---
title-block-style: plain
date: 11/01/2021
date-modified: last-modified
---

# Primary Protocol {#sec-primary}

## Introduction

Below, we provide a straight-forward and broadly applicable protocol to achieve project goal of quantifying variability in plant-herbivore interactions. This is HerbVar’s Primary Survey Protocol. In brief, 30 randomly selected plant individuals in a site (\~population) are surveyed for herbivore damage and (possibly) herbivore abundance. Data are also collected on the nearest conspecific neighbor of each plant (for a total of N = 60 plants). These methods yield estimates of variability, skew, and spatial patterns (e.g., autocorrelation) in herbivore damage. 

::: {.callout-important title="Alternatives to the Primary Protocol"}

The HerbVar Primary Survey Protocol is designed to work for many common plant growth forms and contexts, so we expect most surveys to use this protocol. The primary protocol, however, will not work for every plant growth form or context, so HerbVar has multiple alternative survey protocols. These include protocols for surveying the following:

-   Reproductive damage: @sec-repro
-   Low density/abundance populations: @sec-low_density
-   Cacti and other succulents: @sec-succulents
-   Mature trees: @sec-tree *(surveys of immature trees (i.e.,
    seedling/saplings) use the Primary Protocol below)*
-   Rhizomatous geophytes: @sec-rhizo
-   Insect herbivores, galls, and mines: @sec-herbivore

:::

If the Primary Protocol is not feasible for a species or site, then we
suggest one of the alternative protocols. If none of these alternative
protocols fits the situation, then collaborators may deviate from the
primary protocol. We trust collaborators to decide how to adapt the
primary protocol in ways that work for their systems. We suggest,
however, that collaborators strive to follow the spirit of the protocol
below: randomly select at least 30 plants from a site and census them
and their nearest neighbors for herbivory and herbivore data. For a
dataset to be usable in the overall study, it will have to be comparable
to data collected using this protocol. Collaborators who deviate from
the HerbVar protocols should carefully record their methods.

## Preparing to Sample

### Select a plant species

From the patterns found in the first phase of data collection we have
developed the following objectives going forward:

1.  Surveys of the three focal species (*Taraxacum officinale*,
    *Plantago lanceolata*, and *Plantago major*), especially across
    broad environmental and/or geographic ranges

2.  Surveys of species in the five focal families (Apocynaceae,
    Asteraceae, Fabaceae, Rubiaceae, and Solanaceae). We want surveys of
    new species within these families, especially species from new
    clades or with unusual growth forms. For repeat surveys of species
    within these families, we are prioritizing surveys from new regions,
    habitats, elevations, etc.

3.  Surveys of damage to any species’ reproductive tissues (e.g.,
    flowers, fruits, etc.).

While we welcome all surveys, data that fall under one or more of these
three guidelines is particularly valuable in addressing the current
scope of HerbVar’s research questions. Please refer to our more detailed
HerbVar Species Selection Protocol for more information on species
selection and how data contribution relates to authorship in papers
utilizing those data.

#### A note on the ideal abundance of focal plants

The primary protocol works best for sites with at least \~90 plant
individuals, such that it makes sense to sample individuals randomly. If
your site has fewer than \~90 individuals of your plant species, then
please consider comprehensively censusing all individuals within the
site as suggested in the Low Density/Abundance Protocol. A comprehensive
census, when feasible, would be even better than the protocol below. If
plants are far enough apart, please take GPS coordinates for each plant.
If a comprehensive census is not feasible, then please modify the
primary protocol or the low-density/low-abundance guidelines to work
efficiently with your species and site. Please reach out to the HerbVar
coordinators if you have questions or want to check that your
modifications will lead to adequate data.

### Learn to Estimate Herbivory 

**First, review HerbVar’s Damage Estimation Training Guidelines** (see @sec-damage). Note that information on precision of estimates and acceptable binning is contained in this document This document contains valuable information on how to estimate percent damage on various leaves. **Next, train and test team members with the [ZAX Herbivory Trainer](https://zaxherbivorytrainer.com/)**. This web-based application, created by Dr. Angela Moles and Zoe Xirocostas, provide a risk-free environment for testing oneself on per-leaf damage estimation Note that the app prompts you to assess damage to the nearest percent while our protocol is slightly coarser (see @tbl-herbiv of the Damage Estimation Guidelines). The app has two stages, one in which you assess damage and are immediately told how close you are to correct and a second where you assess 50 leaves, and the results are given to you at the end. Please feel free to focus on the first part of the app until you are confident (though you are of course welcome to do the second if you want extra training). Finally, **download and familiarize yourself with the datasheets for this protocol**. There are digital (see siteData, densityData, and plantData sheets) and printable versions to facilitate standardized data entry.  If you have a question, feel free to reach out to [herbvar\@gmail.com](mailto:herbvar@gmail.com).

### Site Selection & Delineation

A “site” should be an area where a given plant species occurs at a high enough density to easily select 30 focal plants and 30 unique neighbors with our method. We can use any site anywhere around the world, but the most valuable sites will represent geographic regions, environmental conditions, habitats, or other ecological characteristics that we do not currently have in our database or that are currently poorly represented in our database. This is especially important for our focal species and re-surveys of other species we already have in our database. It’s less important for new species, especially when those new species are from clades that we do not currently have in the database.

We realize that defining the ‘edges’ of a site can be subjective and not easy. We search for an area where a given plant species occurs at a high enough density to easily select 30 focal plants and 30 unique neighbors with our method. This is usually a relatively dense patch. Walk around and see if you see the density drop off to well below the mean density that is used to calculate radius size. This is usually quite simple, e.g., when we walk out from the center of a “site” and don’t see any individuals of the focal species within 5 m, we decide we’re at the edge of a patch. In some systems, delineating a single, sampleable population simply might not be possible (e.g., where a species covers a vast area). In these cases, collaborators should simply do their best to select a reasonable, representative area to sample.

### Pick a time to sample

This will depend on the natural history of the system. We will accept
data sampled at any time as long as there has been some herbivory. We
will use the sampling date to examine how herbivory changes seasonally
(please note approximate dates for beginning and end of growing season
for each survey, see siteData sheet in datasheet template). However, the
most valuable surveys will be after enough time has passed for an
ecologically meaningful amount of herbivory to accumulate. In strongly
seasonal systems, this will be in the latter half of the growing season.
But it could also be once leaves have reached maturity (e.g., for
species in which most herbivory is on expanding leaves). In other
systems, the best time to sample might be during or after a key life
history stage (e.g., flowering). All that said, there is no perfect time
to sample. Collaborators should use their knowledge to decide when to
sample (and sample when is feasible; some data is better than no data!).
And repeat sampling is acceptable.

### Determine a radius for your circular quadrats  

a.  **If you are sampling one of the HerbVar focal species**
        (_Taraxacum officinale, Plantago major, Plantago
        lanceolata_): Use a radius of 0.4 m for your quadrats. This
        will standardize across surveys of these same species. Note that
        if your populations are sparse, you may use a larger radius
        following the other process or pre-calculated values (@tbl-radius).

b.  **If you are using any other species**, use the following process to determine a quadrat radius or use the table below:

      1.  Estimate mean density of plants (plants per m$^2$)
      2.  Count the number of plants in 1 m$^2$ at 10 random locations
            within the site
      3.  Calculate mean plant density (*_D_*)
      4.  Use *_D_* to calculate a circular quadrat radius (*r*) that
            would on average contain 4 plants *r* = 4/(π*_D_*).
      5. This approach seeks an optimal, intermediate quadrat size that balances the costs associated with a small quadrat size (many empty quadrats) and a large quadrat size (quadrats that require counting many plant individuals).
        
c. Instead of calculating as above, you may also use this pre-calculated set of radii (@tbl-radius) for non-focal species. ***Remember, for focal species, please use 0.4 m***

: Table 1. Pre-Calculated Quadrat Radii {#tbl-radius}

| **Plant Density (_D_: plants / m^2^)** | **Quadrat radius (_r_: meters)** |
|----------------------------------|----------------------------|
| _D_ ≤ 0.1                          | 3.6 m                 |
| 0.1 \< _D_ ≤ 0.25                  | 2.9 m                      |
| 0.25 \< _D_ ≤ 0.5                  | 1.9 m                      |
| 0.5 \< _D_ ≤ 1                     | 1.35 m                     |
| 1 \< _D_ ≤ 3                       | 0.9 m                      |
| 3 \< _D_ ≤ 6                       | 0.55 m                     |
| 6 \< _D_ ≤ 10                      | 0.4 m                      |
| 10 \< _D_ ≤ 20                     | 0.3 m                      |
| 20 \< _D_                          | 0.23 m                     |



## Sampling

1.  Lay a transect through the middle of the site (@fig-sampling). Record (i) the GPS coordinates of the transect origin, and (ii) the length (m), and compass direction (degrees) of transect (need to pick a coordinate system and precision)

2.  Select center points of circular quadrats (@fig-sampling). Randomly select 40+ points in the site by selecting pairs of random numbers. One random number represents distance along the transect (0–length of transect); the other represents distance left or right of the transect (left=negative, 0=center, right=positive). These are the center points of quadrats.

3.  For each quadrat: 

    a.  Locate a quadrat center point using transect and measuring tape or
    stick (@fig-sampling)  

    b.  Count and record the number of focal plants within r meters of the
    center point (@fig-sampling).  
    
        i. See above for explanation of how to calculate _r_ (or use values in @tbl-radius). 
    
        ii. It may be helpful to place a stick vertically in the center of the quadrat, attach a string of r meters to the tip, and walk in a circle around the stick to help visualize the circular quadrat
    
        iii. **Note:** this includes only rooted focal plant species individuals in the quadrat

4.  Record other quadrat-level data

    a.  **Percent cover of focal plant species** (ignore non-focal species).
    **Note:** this includes both rooted and not rooted focal plant
    species individuals in the quadrat but hanging over the edge from
    above
    
    b.  **Percent cover of all non-focal plant species** (ignore focal
    species) 

        i. These 2 percent covers could total more than 100% if they overlap

        ii. If surveying understory plants, ignore forest canopy when estimating percent cover


5.  If the circular quadrat has 0 plants, record a zero and continue to
    the next quadrat

6. If the circular quadrat has \> 0 plants: Randomly choose 1 of the
    plants within the quadrat to survey A quicker alternative would be
    to choose the plant closest to the quadrat center. But this is
    recommended only if you think it will produce an unbiased sample of
    plants from your site. Be careful about over-representing large
    and/or isolated plants (which will be closer to more points relative
    to small plants in crowded patches).

7. For the selected plant (1 per quadrat) record plant life stage i.e.,
    seedling, vegetative, flowering, fruiting Note that if multiple
    stages are present, record all relevant stages (i.e., a plant can be
    both flowering and fruiting)

8. For the selected plant record plant size. Use judgment to pick best
    measure for your species e.g., standing plant height (ground to
    tallest living part), stem length, foliage diameter, stem diameter

9. **Perhaps most importantly:** for the selected plant record herbivore
    damage in 3 ways (see Damage Estimation Training Guidelines) Note
    that “herbivore damage” includes damage caused by both vertebrate
    and invertebrate herbivores.

    a.  Presence/absence of leaf damage: Record both the total number of leaves on the plant and the number of leaves with \>0.5% herbivory 
    
        i. If the plant has ≤ 60 leaves total, please record the true numbers  
        
        ii. If the plant has \>60 leaves total, randomly (arbitrarily)
    choose 60 and record those values. Please also make a note that you
    stopped at 60 (see template datasheet). 
    
      **_Note that we are no longer including undamaged leaves in the following step_**, so these two data points are vital in understanding the proportion of the plant that is not damaged by herbivores. 
    
10. If plants have reproductive parts (flowers/fruits/seeds) that could have been damaged by herbivores, please see the Reproductive Damage Protocol. This is optional but encouraged.

11. Estimated percent damage on 10 randomly (arbitrarily) chosen leaves with herbivory damage (\> 0% herbivory) 
    
    a. One estimate per leaf (for a total of 10 estimates). 
    
    b. Please strive to sample in a way that selected leaves will be representative of all leaves on the plant (e.g., sample young and old leaves in proportion to frequency on plant) 
    
    c. If desired, you may use an application to estimate damage (e.g., LeafByte, etc.). However, please make a note of that in the appropriate part of the siteData tab of the template datasheet.  
    
    **Note that all selected leaves should have \> 0% damage** (this is a change from the Phase 1 protocol). Note also that measuring only damaged leaves makes the data collected in step 1 (see above) vital in understanding per-plant damage variation. 
    
    d. For leaves with herbivore-built leaf shelters (rolls and ties), please carefully peer into or open shelters to estimate damaged area and count resident herbivores 
    
    e. If damage is estimated visually and leaves are visibly damaged but \< 0.5% (i.e., damage \> \~0.1% but ≤ 0.5%) record 0.5%. If a leaf has \< \~0.1% damage, round that down to zero. If using an app, make a note and put in the value the app provides.

12. **Estimated percent damage across the whole plant,** optionally also
breaking apart damage by type or even species of herbivore if possible
(e.g., sucking damage versus chewing damage, add columns as needed). 

    a. E.g., If a plant has 4 equally sized leaves and 2 of those leaves are
50% eaten, then whole plant has 25% herbivory 

    b. But take leaf size into account when leaves vary in size 

    c. **If this measure is not feasible to collect, measure 30 leaves** instead of 10 in step 2 (see above) and leave this blank. Those 30 can then be used to calculate this value post hoc

14. Record presence of plant diseases (i.e., pathogens) 

    Please also estimate your confidence in your pathogen estimate and include it as a note in the provided column in the datasheet. In Phase 1, several collaborators pointed out that the difference between pathogen pressure and nutrient deficiency can be slim so this confidence estimate will be helpful in accounting for the difficulty in pathogen estimation

15. Record number of leaf mines and galls per plant 

    a. If there is reason to believe that galls or mines have accumulated through multiple years (e.g., stem galls on woody perennials), please note this 

    b. If there are too many mines or galls to count individually, estimate the number per plant by tallying the number per module (e.g., stem, branch) and multiplying by number of modules 

    c. If serpentine/linear mines cannot be confidently recorded, instead count only blotch mines to record a consistent mine abundance (see visual guide at bottom of Herbivore Sampling Protocol for definitions of “serpentine” versus “blotch” mines) 

    d. **_Optional:_** abundance of other externally-feeding herbivores (standardized approach; see Herbivore Sampling Protocol to decide if/how to collect these data)

16. Distance to nearest conspecific neighbor (where the nearest neighbor
    is the plant with the closest above ground tissue to any aboveground
    tissue on the focal plant)

17. Data to record for the first nearest conspecific neighbor of
    selected plant: All the same data as focal plant except nothing for
    neighbor’s neighbor

18. Continue visiting the randomly selected points until ≥ 30 focal
    plants and 30 nearest neighbors have been surveyed


![A diagram of the sampling scheme described in the text. (1)
Record plant density in 10 randomly located 1-m2 areas to estimate
average plant density D, which is used to calculate quadrat radius r.
(2) A quadrat with one focal plant and its nearest neighbor (outside
quadrat). (3) A quadrat with no focal plants. (4) A quadrat with 5 focal
plants; plant 3 is randomly selected for data collection, and its
nearest neighbor is plant 4. Diagram by Moria
Robinson.](images/img1.png){#fig-sampling}


## After the Field

1.  Enter your field-collected data into the template Excel file. Refer
    to the data Dictionary sheet if column meanings are unclear

2.  Use the data submission portal to upload your data The portal has
    numbered steps to assist the upload process.

3.  After uploading via the submission portal, check the Completed
    Surveys file to ensure that your data were uploaded successfully.
    Uploaded data will have your entries in the sidebar of the app as
    the bottom-most row of that file


## Methods Notes

1.  Modifications of this protocol may be necessary to adapt it to
    different systems (see “Alternate Protocols” box above). If the
    primary protocol won’t work for your system, please first consult
    our alternative protocols. If our alternative protocols do not solve the issues, then you may adapt the primary protocol as needed. **Whatever you do, please record methods carefully and strive to follow the spirit of the protocol and produce comparable data.**

2.  In Phase 1, collaborators reported that one survey (\~60 plants)
    took between 0.5 and 2 person days (4-16 hours) using the methods
    above (after a species and site have already been selected).

3.  We select 40 quadrat center points (instead of 30) so that we have
    extra points ready in case some quadrats are empty. If you predict
    that many quadrats will be empty (e.g., in a very spatially clumped
    population of plants), then select more points (e.g., 60 points).
    (Remember the goal is to have 30 focal plants sampled, plus their
    nearest neighbors).

4.  Sometimes, especially in small populations, a focal plant ends up
    being another focal plant’s neighbor. This is fine. Just note and
    keep going. If you have time, you can add an extra focal plant at
    the end (but this isn’t totally necessary).

5.  For clonal plants, we have been calling stems “individuals” if they
    are not connected aboveground. When looking for above ground
    connections, we clear away detritus, but we do not dig or move soil.
    There is also a dedicated alternate protocol for surveying such
    species (see Rhizomatous Geophytes Protocol)

6.  Please see our Damage Estimation Training Guidelines for guidelines
    on how to estimate herbivore damage. Here are two tips:
    
    a.  Sometimes discerning herbivore damage from physical damage (e.g.,
    wind, trampling) is tricky. We do the best we can. We look at things
    like how jagged the cut edges are and if they travel past the
    missing area into the remaining leaf tissue (which would suggest the
    damage may have been physical).

    b.  Another challenge is old damage that occurred when leaves were still expanding. This could potentially make the area removed seem larger than it was. If we suspect something like this happened, then we try to bend the leaf back into shape to see if it seems like the missing area expanded over time.

7.  We will accept surveys that only assess damage and do not identify
    herbivores. This will allow people without insect ID skills to
    participate in the study.


## Common Garden Data

Common gardens are a powerful tool for studying plant–herbivore
interactions. Several collaborators have proposed including them in
HerbVar, and we would like to try if we can get enough data. To be
applicable to this study a common garden’s design would have to be
random with respect to genotype. If a garden was somehow stratified with
blocks containing repeated instances of, e.g., different levels of leaf
toughness, then damage distributions will not be comparable to damage
from wild populations. We may still be able to use such datasets, but
only if we have enough to use them in a separate analysis. Please get in
touch if you would like to contribute common garden data.

