---
author: Yuval Sapir (Tel Aviv University)
---


# Rhizomatous Geophytes {#sec-rhizo}



## Overview

Clonal plants present an interesting challenge and opportunity within the HerbVar Network. From a question-based perspective, we may be able to compare patterns of herbivory variability between clonal vs non-clonal plant species. These different modes of reproduction may confer different levels of genetic and phenotypic diversity within plant populations, which could affect patterns of herbivory. However, from a practical perspective, quantifying herbivory among plant ‘individuals’ is a challenge in these systems (i.e., what constitutes an ‘individual’?). 

## Objectives

Provide a protocol for surveying herbivory on a rhizomatous plant species that meets two conditions: (1) it is feasible to determine what constitutes a genet by examining rhizomatous connections, and (2) genets are small enough at your study site that you could feasibly survey 30 genets and their nearest neighbors and estimate herbivory on each genet.

## Background

In semi-arid and arid climates, a considerably large number of plant species are rhizomatous geophytes. Their major characteristic is that they grow as patches of individuals, forming either dense (phalanx) or sparse (guerrilla) mats of individual ramets, each visible as a single leaf fan, and all connected through below-ground rhizomes and/or above-ground stolons into one plant (genet) (terms following Harper 1977 and Herben and Klimešová 2020). The extent of clonal growth defines the spread of the genet, and is on a continuous scale of density (Vallejo-Marin et al. 2010). See Figure 1 for examples of two density levels of genets in irises.

## Protocol – Rhizomatous Geophytes

1. When first starting this for a new species or at a new site, we suggest spending time investigating what constitutes a genet. Follow rhizome connections from ramet to ramet to get a sense of what a single genet looks like before following the rest of this protocol.

2. Follow the Primary Protocol & Site Selection Protocol to pick a site, set up a transect, and randomly select focal quadrats’ locations

### Calculate a custom radius for circular quadrats

Estimate mean density of genets per square meter by counting the number of plants in 1 m2 at 10 random locations within the site

- If genet area (clone/genet diameter) is >1 m and/or distances between genets are apparently irregular (that is, secondary dispersion of plants within population is patchy), count the number of genets in 1 m2 every 5 meters along a 50 m transect.
- If a quadrat has >0 focal plants, randomly choose 1 of the genets to survey and record the following data:

### Genet life stage: seedling, vegetative, reproductive

Genet size, measured as the height of the tallest leaf for plants in vegetative stage, or height of the taller flower for plants in reproductive stage. Record which metric you used in the “plantSizeMetric” column

### Herbivore damage in one of 3 ways:

1. Total number of leaf fans (ramets)

- For genets with >100 ramets, write “100” and make a note that your estimate was capped at 100
Estimated percent damage across the whole genet. Visually scan all the green areas of all ramets and all leaves, and estimate the percentage of damage.

- If the plant has <10 ramets, sample all ramets. From each chosen ramet, pick the 2nd or 3rd leaf from top and estimate percent herbivory. These leaves are putatively in the same developmental stage and are the same age, thus exposed to herbivory for equal time

Note that tip of the leaf may be dry due to climate fluctuations in the arid regions. This area of dry leaf counts as leaf area, but not as herbivory damage

2. If a quadrat has 0 focal plants, record a 0 and move to the next quadrat

3. Record the same data for the first nearest conspecific neighbor (of a different genet) that you recorded for the focal plant.

4. Continue visiting randomly select points until ≥ 30 focal genets and 30 nearest neighbor genets have been surveyed


*Figure 1* – Top left: Dense (“phalanx type”) genet of Iris atrofusca; Top right: Sparse (“guerrilla type”) genet of Iris bismarckiana; Bottom left: Compact rhizome of Iris atrofusca (this one has ~4 leaf-fan ramets); Bottom right: Stolons connecting ramets of Iris bismarckiana.


### References

Harper, J. L. 1977. Population Biology of Plants. Academic Press, London.

Herben, T., and J. Klimešová. 2020. Evolution of clonal growth forms in angiosperms. New Phytologist 225:999-1010.

Sapir, Y., and A. Shmida. 2002. Species concepts and ecogeographical divergence of Oncocyclus irises. Israel Journal of Plant Sciences 50:S119-S127.

Vallejo-Marin, M., M. E. Dorken, and S. C. H. Barrett. 2010. The Ecological and Evolutionary Consequences of Clonality for Plant Mating. Annual Review of Ecology, Evolution and Systematics 41:193-213.

Wilson, C. A., J. Padiernos, and Y. Sapir. 2016. The royal irises (Iris subg. Iris sect. Oncocyclus): Plastid and low-copy nuclear data contribute to an understanding of their phylogenetic relationships. Taxon 65:35-46.

