# Species & Site Selection (Phase 2) {#sec-species_site}

# MOST RECENT UPDATE: 

## Overview

Based on Phase 1 of data collection, we ask that you prioritize the following 3 sampling objectives in your site and species selections for Phase 2 of data collection:

### Species Objective 1: Focal species across gradients

**Goal: **Sample our three focal species (_Taraxacum officinale_, _Plantago major_, and _Plantago lanceolata_) across broad geographic and/or environmental gradients.

**Justification: **Sampling within these three species will increase the depth of our understanding of the effects of particular abiotic gradients (e.g., elevation, precipitation, temperature, etc.) as drivers of variability in herbivory pressure within plant species. Each species is standardized within itself so studies of herbivory across a range of contexts allows for strong inference on the effects of those contexts.

### Species Objective 2: Novel species & contexts within focal families

**Goal: **Sample species from novel clades or with atypical growth forms within our five focal families (Apocynaceae, Asteraceae, Fabaceae, Rubiaceae, and Solanaceae). Surveys of plant species that were included in Phase 1 are also welcomed but should prioritize novel regions, habitats, or environmental contexts.

**Justification:** Increased resolution within our five focal families allows for testing of drivers of herbivory variability in a phylogenetically-explicit framework. Understanding the impact of evolutionary differences within these families on the distribution of damage will be crucial in teasing apart macroevolutionary patterns.

### Species Objective 3: Damage to Reproductive Tissues

**Goal: **Survey damage to any species’ reproductive tissues (e.g., fruits, flowers, seeds, etc.).

**Justification: **Damage to reproductive structures has–arguably–the most direct impact on fitness so an understanding of the drivers of variation in herbivory damage to reproductive tissues is crucial for understanding population-level or fecundity-related consequences of herbivory variation.

### Site Selection Guidelines

**Goal: **A “site” should be an area where a given plant species occurs at a high enough density to easily select 30 focal plants and 30 unique neighbors with our method. We can use any site anywhere around the world, but the most valuable sites will represent geographic regions, environmental conditions, habitats, or other ecological characteristics that we do not currently have in our database or that are currently poorly represented in our database. This is especially important for our focal species and re-surveys of other species we already have in our database. It’s less important for new species, especially when those new species are from clades that we do not currently have in the database.

**Further Explanation: **We realize that defining the ‘edges’ of a site can be subjective and not easy. Walk around and see if you see the density drop off to well below the mean density that is used to calculate radius size (see the Primary Protocol). This is usually quite simple; for example, when we walk out from the center of a “site” and don’t see any individuals of the focal species within 5 m, we decide we’re at the edge of a patch. In some systems, delineating a single, sampleable population simply might not be possible (e.g., where a species covers a vast area). In these cases, collaborators should simply do their best to select a reasonable, representative area to sample.
