---
author:
  - name: Judie Bronstein
     affiliations:
      - ref: ua
      - name: University of Arizona
        city: Tucson
        state: AZ
  - name: Victoria Luizzi
    affiliations:
      - ref: ua
      - name: University of Arizona
        city: Tucson
        state: AZ
title-block-style: plain
date: 11/01/2021
date-modified: last-modified
---
# Cacti & Succulents {#sec-succulents}

## Overview

This document discusses issues relevant for quantifying herbivory on cacti and outlines a hopefully widely applicable protocol for doing so. The protocol is designed for cacti that have many jointed segments, but we also discuss ways to modify the protocol for other architectural types. Although we focus on cacti, we think this document will also be helpful for other succulents. Please share feedback, particularly ways we can make this widely useful.

**Unique Context: ** With regard to quantifying herbivore damage, cacti are special: (a) they are architecturally unique, (b) architecturally distinct from each other, and (c) much of the herbivory is surficial (there are few “edges” to bite!) and (d) since units are not lost, damage can persist for decades. Any census method needs to take these factors into account.

## Sampling Issues within Architectural Categories

Cacti can be thought to consist of one or more (usually spiny) tubes with flowers usually located at the tip of the tube – that’s what they have in common – with these tubes having a diversity of spatial relationships to each other – that’s what makes them different from each other. **_There are at least five categories, each with its own herbivory sampling issues_.**

1. **Single, unbranched tube stuck in the ground** (e.g., in the American Southwest, a barrel or a pincushion cactus).  As they age, they get taller and wider, but they never branch or clone. If there is a cluster, they are genetically different from each other (I am almost sure, JB).  

    **Entire structure should be scrutinized for herbivore damage**. When these cacti form a cluster, they should be categorized as multiple individuals rather than as a single individual.  

2. **Set of unbranched tubes connected underground** (e.g., a hedgehog cactus (small), or a senita or organ pipe cactus (large)). They add units as they age. 

    **Either the whole thing can be scrutinized for damage, or a subset of units could be (please make a note of which path you chose)**. If there are not that many units, full sampling is possible. However, some of these cacti get very tall. Since much damage seems to accrue at tube tips, one really should look at the entire length.

3. **Tube that starts to branch above the ground** as it ages (e.g., a saguaro cactus).

    **Same method as #2** (again, please make a note of whether you examined the whole plant or a subset of units).

4. **Large set of tubes connected at distinct joints** (e.g., a cholla cactus). New tubes are added as the plant ages.

    **Subsampling within individuals will usually be necessary** because individuals often have many tubes. Our protocol below, which is focused on cacti with many joints, describes a method for subsampling up to 20 joints per plant.

5. **Large set of tubes connected at distinct joints _but flattened into pancakes_** (e.g., a prickly pear cactus). New tubes are added as the plant ages.

    Same method as #4.

## Expected Types of Herbivory

1. **Bites that remove chunks of flesh.** This is quite obvious for the fifth category of cacti (flattened pads), because the pads have smooth edges that will be disrupted by this type of herbivory. So if this category is being surveyed, special attention should be paid to the edges of pads. I am not sure if it will be evident, or at least common, for any other category: only this category consists of units with “edges”. I suspect that other cactus-feeders that take out chunks of flesh concentrate on the youngest tissue (new units and the tips of existing units), and this suggests important sampling rules: young units should be sampled, as well as tips of existing units (which, unfortunately, might be very high in the air). Some large beetles burrow into cactus flesh, but (based on my knowledge of barrel cactus) these individuals rapidly die, so this sort of damage is unlikely to persist

2. **Scarring of the surface of the cactus.** It can be very hard to know what causes this – some of this damage may be attributable to herbivores, but some might be fungal or bacterial attack. It is worth taking photos of the damage and trying to figure out the culprit. Damage left by various small herbivores on various cactus species has been described in the literature and it may be worth making a photo album for later identification.

3. **Colonies of sucking insects.** In particular, cochineal bugs live in colonies and are exciting to see. They are covered with a messy white wax. At least in the desert Southwest, cochineal are primarily found on introduced Opuntia ficus-indica. However, there are small colonies on Opuntia englemanii as well that should be watched out for.

## Additional Considertations 

1. **Some genera have species with extrafloral nectaries (EFNs).** Most (not all) barrel cacti have them, and I believe all columnar cacti (senita, organ pipe, saguaro), prickly pear, and cholla do. On the other hand, I don’t know of any hedgehog or pincushion cacti that have them. Ant attraction to extrafloral nectaries may reduce herbivore attack, though field evidence for this has varied across cactus species, and ants are often surprisingly rare. Most EFN-bearing cacti only secrete nectar when there is new vegetative growth, buds, flowers, and early fruit present, but some (such as the fishhook barrel cactus abundant in Tucson) secrete it year-round.

2. It seems likely that the **newest, tenderest units are particularly likely to be attacked** (particularly in categories 4 and 5 cacti).

3. The **buds and young fruits of some cacti get very heavily attacked**, and these should be included by counting damaged and undamaged units and recording the data separately (see Reproductive Damage Protocol).

## Protocol

We designed this with prickly pear (_Opuntia_ spp.) in mind, but it should work essentially the same way for other cacti with many jointed tubes such as cholla (_Cylindropuntia_ spp.). Modifications will be necessary for some cacti. _The gist of the protocol involves following the Primary Protocol except for a subsampling of leaves and reproductive units (if present) within plants_. We suggest taking both this protocol and the Primary Protocol with you in the field.

### Pre-Census Tasks

1. Pick a species to census.

2. Choose a site, ideally with at least 90 well-defined individuals that you can randomly sample using the HerbVar Primary Protocol. If your site has fewer than ~90 individuals or has very widely spaced individuals, we suggest following methods from our document on Surveying low-density/low-abundance sites.

3. Decide on a maximum number of pads per plant to census.

4. We recommend focusing only on young cactus pads. But you should decide if this will do a good job representing the plant-herbivore interaction and distribution of herbivory for your species. By young pads we mean those that are final joints, i.e., that don’t have another pad growing out of them. Problems with older pads include:

    a. Older pads can be many years old, thus integrating herbivory over a much longer time than happens for other plant species in HerbVar (few plants hold leaves as long as cacti hold their pads)

    b. Practically, it’s very hard to determine and quantify what is herbivory vs physical damage on older pads

    c. Physically, it can be hard and dangerous to access older pads on spiny plants!

    d. If you think focusing on young pads will not be good for your species, then please modify the protocol to include older pads. 
Take detailed notes.

5. Ideally, investigate the major types of damage you may see, potentially making a cheat sheet of photos.

6. See how long the protocol outlined below would take, then modify as necessary. Be sure to take detailed notes on any modifications made to the protocol.

### Census

1. Record site characteristics (e.g., date, site, plant ID, etc.)

2. Review above discussion of architectural categories of cacti/succulents and decide how you will define an individual plant. Past populations we surveyed had many very large clumps of pads that were almost certainly one plant individual, though not all connections were visible aboveground. In most cases, the clumps were discrete enough that we were confident each clump was one individual with below ground connections. 

3. If you have a site with >90 plant individuals, follow the Primary Protocol from the beginning until you have your first plant for herbivory estimation. Briefly: 

    a. Pick transect and subtransect distances that will encompass your site and lay the transect through the site.

    b. Estimate the density of plants in the population.

    c. Use the estimated plant density to calculate a quadrat radius to use for the survey.

    d. Randomly generate x,y points, visit them, and set up a quadrat centered on each random point, selecting 1 plant randomly within each quadrat. See the Primary Protocol for more detail.

4. Once the first plant is selected, survey it for herbivory. For vegetative herbivory, we recommend focusing only on terminal pads (see #4 above). Terminal pads are those at the end of a branching structure, without another pad growing out of them. Also, focus only on the visible surfaces of pads because moving spiny pads safely is difficult and time consuming! **Record herbivory from all organisms in one column and herbivory you are certain was just from insects in a second column**. We found it was difficult to distinguish insect herbivory from vertebrate herbivory, so we usually recorded “totalHerb” Occasionally it was clear some herbivory was just from insects, so then we used the “insectHerb” column to indicate what percent was definitely from insects. **There are 3-4 herbivory estimation steps, depending if your plant has reproductive organs:**

    a. Quickly scan all of the terminal pads across the entire plant and visually estimate percent herbivory. This is a quick estimate, but it’s important to scan the whole plant because herbivory can be patchy within plants. 

    b. Randomly select 20 of the terminal pads. Record the number of pads you examined and the number with any herbivory present. If there are fewer than 20 pads on the plant, then do all pads. 

    c. Randomly select 10 terminal pads, and record a visual estimate of the percent herbivory on each pad, resulting in 10 numbers (one number for each of the 10 pads). We estimated percent herbivory as surface area removed on the visible faces of paddles (as opposed to volume or doubling the area for holes that went entirely through a paddle).

    d. If your plant has reproductive organs, please randomly (arbitrarily) select up to 20 units of one type (e.g., flowers or fruits) and record the number of units you examined and the number that were damaged (>0.5%). Please see the Reproductive Damage Protocol for more information. You will need to add columns to the HerbVar Template Datasheet to accommodate this.

5. Note presence of pathogens.
