 ---
title: Herbvar Products
date-modified: last-modified
---

```{r}
#| echo: false
#| warning: false

# pull the publications and presentations from Zotero via api
# with Refmanager (see
# https://docs.ropensci.org/RefManageR/index.html)
library(RefManageR)
library(knitr)
library(markdown)


# need to figure out how to save the temp .bib files to the root directory so always have latest version of bib file in repo

pubs<-ReadZotero(group = "5539815",
           .params = list(key = "p7F1H0PRo5JpntQLrESjj1al",
                          collection = "K4QE2MGT"),
           temp.file = tempfile(fileext = ".bib"),
           delete.file = TRUE)





pres<-ReadZotero(group = "5539815",
                 .params = list(key = "p7F1H0PRo5JpntQLrESjj1al",
                                collection = "7M4HYQEI"),
                 temp.file = tempfile(fileext = ".bib"),
                 delete.file = TRUE)

# set the options for the bibliography
BibOptions(check.entries = FALSE,
           style = "markdown",
           bib.style = "markdown",
           cite.style = 'html',
           hyperlink="FALSE",
           no.print.fields= c("url", "isbn","urldate",
                              "issn","language",
                              "extra","note")
)

```
# Publications {.unnumbered}

**A .bib file of all HerbVar publications is available for download** [**here**](https://raw.githubusercontent.com/HerbVar-Network/herbvar_manual/119c8fa09dddde13b44165105d3d3f977c35e568/project_publications.bib?token=GHSAT0AAAAAACX4VYS4DTF66PLV5GVWP6DCZYGXN5A).

```{r}
#| echo: false
#| warning: false
#| results: asis

n_pubs<-length(pubs)
NoCite(pubs[1:n_pubs])
  PrintBibliography(pubs,
                    .opts = list(style = "markdown",
                                      bib.style = "authoryear"))

```


# Presentations {.unnumbered}

**A .bib file of all HerbVar presentations is available for download** [**here**](https://raw.githubusercontent.com/HerbVar-Network/herbvar_manual/refs/heads/main/project_presentations.bib?token=GHSAT0AAAAAACX4VYS42HAPGEYMRUA6F7F2ZYGXO6A).

```{r}
#| echo: false
#| results: asis

n_pres<-length(pres)
NoCite(pres[1:n_pres])
  PrintBibliography(pres, .opts = list(style = "markdown",
                                      bib.style = "authoryear"))
```





::: {#refs}
::: 
