 ---
title: Herbvar Products
date: today
---


# Publications {.unnumbered}

**A .bib file of all HerbVar presentations is available for download** [**here**](https://raw.githubusercontent.com/HerbVar-Network/herbvar_manual/refs/heads/main/project_publications.bib?token=GHSAT0AAAAAAC2ASX4DDIAV62IX3MHNIRPQZZKNNXQ).


Pan, V. S. and W. C. Wetzel (2024). “Neutrality in plant–herbivore interactions”. In: Proceedings of the Royal Society B: Biological Sciences 291.2017, p. 20232687. [DOI: 10.1098/rspb.2023.2687](https://royalsocietypublishing.org/doi/10.1098/rspb.2023.2687.

The Herbivory Variability Network* †, M. L. Robinson, P. G. Hahn, et al. (2023). “Plant size, latitude, and phylogeny explain within-population variability in herbivory”. In: Science 382.6671, pp. 679-683. [DOI: 10.1126/science.adh8830](https://www.science.org/doi/10.1126/science.adh8830).

Wetzel, W. C., B. D. Inouye, P. G. Hahn, et al. (2023). “Variability in Plant–Herbivore Interactions”. In: Annual Review of Ecology, Evolution, and Systematics 54.1, pp. 451-474. [DOI: 10.1146/annurev-ecolsys-102221-045015](https://www.annualreviews.org/content/journals/10.1146/annurev-ecolsys-102221-045015).


# Presentations {.unnumbered}

**A .bib file of all HerbVar presentations is available for download** [**here**](https://raw.githubusercontent.com/HerbVar-Network/herbvar_manual/refs/heads/main/project_presentations.bib?token=GHSAT0AAAAAACX4VYS42HAPGEYMRUA6F7F2ZYGXO6A).

Bruna, E. M. (2024). _Github as a tool for promoting
reproducibility and collaboration in the HerbVar Network._ HerbVar
Steeting Committee Meeting.

Wetzel, W. C., M. L. Robinson, L. A. Dyer, et al. (2020). _Variability
is a pervasive feature of plant–herbivore interactions: Data from The
Herbivory Variability Network_ virtual meeting.






<!-- ::: {#refs} -->
<!-- ::: -->
