---
title-block-style: plain
date: 11/01/2021
date-modified: last-modified
---

# Network Structure {#sec-structure}

We are a collaborative and inclusive group of researchers who are working together to advance our understanding of plant–herbivore interactions. Membership in HerbVar is determined by participation in data collection and/or significant managerial work, writing or analysis.

## Network PIs

HerbVar is led by the Network PIs:  

- [Will Wetzel](https://wetzellab.com/), Montana State University  
- [Nora Underwood](https://underwood-inouye-lab.weebly.com/dr-underwood1.html), Florida State University  
- [Brian Inouye](https://underwood-inouye-lab.weebly.com/dr-underwood1.html), Florida State University  
- [Susan Whitehead](https://www.speciesinteractions.com/), Virginia Tech, and  
- [Phil Hahn](https://plant-herbivore-interactions.net/), University of Florida  


## Steering Committee

The HerbVar Steering Committee guides the development and implementation of HerbVar policy with input from HerbVar members as needed. This includes the organization of the network, participation guidelines, authorship guidelines and protocols, review of proposals for papers and expanded data collection, and curation of HerbVar data and GitHub tools for working with the data. The Steering Committee is also responsible for producing core papers using the HerbVar data and involving all relevant Site PIs that meet Authorship Guidelines. The members of the Steering Committee are:

- Nora Underwood [nunderwood\@bio.fsu.edu](mailto:nunderwood@bio.fsu.edu){.email}  
- Brian Inouye [binouye\@bio.fsu.edu](mailto:binouye@bio.fsu.edu){.email}  
- Susan Whitehead [swhitehead\@vt.edu](mailto:swhitehead@vt.edu){.email}  
- Phil Hahn [hahnp\@ufl.edu](mailto:hahnp@ufl.edu){.email}  
- Lee Dyer [nolaclimber\@gmail.com](mailto:nolaclimber@gmail.com){.email}  
- Emilio Bruna [embruna\@ufl.edu](mailto:embruna@ufl.edu){.email}  
- Ivalu Cacho [ivalu.cacho\@gmail.com](mailto:ivalu.cacho@gmail.com){.email- }  
- Karen Abbott [kcabbott\@case.edu](mailto:kcabbott@case.edu){.email}  
- Will Wetzel [william.wetzel\@montana.edu](mailto:william.wetzel@montana.edu){.email}



## Members 

HerbVar membership is open to all professionally-trained researchers with expertise in plant-herbivore interactions who plan to collect data or participate in a working group. Members can become Site PIs, can join or lead working groups, or both (see below and @sec-getting_involved).

## Site PIs

Data are collected and contributed by Site PIs and their collaborators or colleagues. Site PIs earn authorship on core papers according to the Authorship Guidelines (see @sec-authorship_process).

## Working Groups

Specific HerbVar goals, projects, and papers are pursued by Working Groups. New working groups will be formed after review and approval by the HerbVar Steering Committee, who will consider their goals and plans for leadership and member recruitment. All HerbVar members are invited to propose working groups for papers based on HerbVar data and/or new types of network data collection. The proposal process typically involves emailing a one page description of the project, including goals, methods, and plans for running the group, to the Steering Committee. For more details, see @sec-data_use_guidelines, @sec-datasets, @sec-new_data_collection, and @sec-authorship_process. Approved working groups will have the support of the network including access to relevant unpublished data, use of pre-written R code for wrangling and cleaning HerbVar data, use of the HerbVar GitHub organization, and publicity for completed work.
