---
title-block-style: plain
date: 09/15/2024
date-modified: last-modified
---

# HerbVar Papers & Authorship {#sec-authorship_process}

## Overview and Philosophy 

The primary goals of the HerbVar authorship process are to consistently, accurately, and transparently attribute the contribution of each author to a paper, to encourage participation in manuscripts by interested scientists, and to ensure that each author has made sufficient contribution to the paper to warrant authorship. Secondarily, authoring a paper within the HerbVar process benefits authors by reducing overlap among papers, fostering collaboration, streamlining use of HerbVar data to produce papers through GitHut tools, and helping to publicize HerbVar products. While prospective authors can use published HerbVar data to create products on their own, we encourage all authors working with HerbVar data to work with the network.

The HerbVar authorship process has been heavily influenced by the authorship process imnplemented by the [Nutrient Network](https://nutnet.org). This process provides ground rules for a fair and inclusive process for establishing authorship while not diluting the value of authorship on a manuscript. HerbVar is grateful to be able to build on the foundation of NutNet’s model for collaborative international ecology. The text below is edited to reflect HerbVar-specific policies, but some is drawn directly from the [NutNet authorship document](https://nutnet.org/authorship). Differences reflect the fact that HerbVar is a much larger network (with hundreds of contributors) and a more fluid network (contributors might only contribute data once, rather than activity maintaining an experimental site). 

## Herbvar Network contributors

The following are definitions for the different types of network contributors:

- **Steering committee:** Responsible for overall network administration. 

- **Site PI:** A contributor that has submitted at least three herbvar surveys for one of the main or add-on objectives. Note that a person can be a site PI for the main objective, but not necessarily a site PI for one or all of the the add-on projects, depending on the completed surveys.

- **Member:** Anyone who is currently or planning to work with the data, either through data collection, working group, etc. 

## Article Categories

In general, HerbVar aims to be as inclusive as possible. At the same time, we acknowledge that massively multi-authored papers (e.g. with all HerbVar members) present substantial challenges for lead authors and might discourage initiation of new projects. To balance these factors, there are two types of published products in the HerbVar process: **“All PI Papers"** and **"Working Group Papers"**. 

### “All-PI” Papers

_All-PI Papers_ invite all site PIs meeting authorship requirements to be co-authors, acknowledging the fundamental importance of contributing data to HerbVar. 

The HerbVar Network launched with a Steering Committee commitment to produce two papers using the core HerbVar data collected during the first phase of sampling. Site PIs earn co-authorship on these papers by providing at least 3 surveys (though more are always welcome) to the core dataset. The Steering Committee has so far launched three add-on projects (Focal Species, Focal Families, Reproductive Damage). Additional add-on projects may be created - see Datasets and Proposals for New Data Collection. Site PIs earn co-authorship on one paper from each add-on project by contributing at least three surveys that advance that project, in addition to the minimum three surveys required for Site PI status and authorship on the core HerbVar papers. See @sec-species_site, [the HerbVar website](www.herbvar.org) and our Species selection document (in the HerbVar Protocols folder) for information on our current sampling objectives and planned manuscripts. We will be flexible on the minimum number of surveys, particularly if substantial additional intellectual contributions are made to project development (e.g., creation of documents and protocols, recruitment of collaborators able to work in under-sampled regions or with under-sampled taxa, or other network coordination work). The Steering Committee will review instances that do not meet the minimum criteria on a case-by-case basis. Please reach out if you have questions or concerns. Collaborators who set out to complete 3+ surveys but are only able to contribute 1-2 surveys will be given the opportunity to maintain authorship by contributing in other ways. Potential contributions that could make up for missing surveys include but are not limited to working on our primary database, developing our traits and/or environmental databases, and/or collecting other metadata. In addition to contributing data, Site PIs who want to be co-authors must also contribute intellectually to at least one of the following: development of questions and overall study design, data analysis or interpretation, writing, or editing. 

Site PIs who contribute data but do not meet the criteria for co-authorship (e.g., submitting too few surveys, deciding to not make up for missing surveys with additional contributions (see criteria for authorship below, etc.) have two options for their data:

1. The Site PI will not be a co-author, but they agree to let HerbVar use and publish the data they contributed. They will be recognized via the HerbVar member list. The HerbVar member list will serve to acknowledge all contributors (even if they didn’t meet co-authorship criteria), and will be associated with each manuscript.

2. The Site PI will not be a co-author, and they do not agree to let HerbVar use and publish their data. All their data will be removed from all HerbVar databases. HerbVar will not use or publish their data. They will be removed from the HerbVar member list.


### “Working Group” Papers

_Working Group Papers_ allow for smaller teams to assemble to write additional papers using HerbVar data, broadening the scope of our collective work without requiring every lead author to manage hundreds of contributors. Typically, working group papers will be centered around already published HerbVar data analyzed in a new way and potentially combined with some new data. HerbVar supports working group paper authors in being as inclusive as is practical, and in connecting with appropriate co-authors to build new collaborations. A complete guide to proposing and writing Working Group papers, along with criteria and expectations for co-authorship, can be found in @sec-worgking-group.

<!-- #### Working Group Proposal & Review Process -->

<!-- If an HerbVar member would like to lead an HerbVar working group paper (i.e., serve as “Lead Author”), they should follow the steps below.  -->

<!-- 1. _Read the authorship policies_ and guidelines below. -->

<!-- 2. _Consult the [HerbVar website](https://herbvar.org/) to review current manuscript proposals and active manuscripts_, and contact the listed lead author on any similar proposal to minimize overlap or to join forces. -->

<!-- 3. _Select an approach_ for forming the working group and inviting co-authors. -->

<!-- 4. _Prepare a manuscript proposal_, and email it to one of the memebers of the [HerbVar Steering Committee](https://herbvar.org/leadership.html). Your proposal should list: -->

<!--    i. the lead author(s) -->
<!--    ii. any other known authors -->
<!--    iii. plans for recruiting additional authors, if any   -->
<!--    iv. the title -->
<!--    iv. the abstract -->
<!--    v. the specific types of data that you wish to use -->
<!--    vi. A brief overview of the response and predictor variables (if appropriate), and -->
<!--    vii. a timeline for analysis and writing. -->

<!-- Proposals are reviewed by the Steering Committee to ensure there is sufficient distinction from proposed and ongoing HerbVar papers. The Steering Committee may suggest altering or combining analyses and papers to resolve issues of overlap. _After receiving Steering Committee Feedback, your proposal will be posted on the HerbVar website._  -->

<!-- #### Following Approval: Research & Writing -->

<!-- _Lead Authors should start work on the project within six months of the approval_ of their project proposal by the Steering Committee. If there are extenuating circumstances that delay the start of work, the lead author should communicate this to the Steering Committee. Extensions can be granted if needed but should be accompanied by a clear timeline.  -->

<!-- Once the proposal for a Working Group Paper is approved, the Lead Authors should: -->

<!-- 1. _Recruit co-authors as planned._ Any invited co-authors should signal their intention to opt-in by responding by email to the lead author before the stated deadline. Lead authors are responsible for communicating regularly with co-authors about progress, including sharing drafts of analyses, figures, and text as often as is productive and practical. -->

<!-- 2. _Create and use a GitHub repository for the paper in the HerbVar GitHub organization._ This will allow the authors to use HerbVar tools for accessing data, for standardizing analyses and manuscript preparation, and for keeping track of co-authors. We ask that authors use our GitHub organization to store and share code and data within their team and with the HerbVar Steering Committee. This helps ensure reproducibility and provides a secure backup for all data, work, and products. -->

<!-- Lead authors and their working groups should submit their paper to a journal within two years. If there are extenuating circumstances that delay paper submission, the lead author should communicate this to the Steering Committee. Extensions can be granted if needed but should be accompanied by a clear timeline. -->

<!-- Lead authors should circulate complete drafts among co-authors and consider comments and changes. Co-authors on papers with large numbers of authors should recognize the final decisions belong to the lead author, given that suggestions from co-authors may conflict. **_Final manuscripts should be reviewed and approved by each co-author before submission_**. -->

<!-- All authors and co-authors should fill out their contribution in the authorship rubric and attach it as supplementary material to any HerbVar manuscript. Lead authors are responsible for ensuring consistency in credit given for contributions, and may alter co-author’s entries in the table to do so. An easy way to manage the author table is with an online spreadsheet. Note that the last author position may be appropriate to assign in some cases. For example, this would be appropriate for advisors of lead authors who are graduate students or postdocs and for papers that two people worked very closely to produce. -->

<!-- The lead author should carefully review the authorship contribution table to ensure that all authors have contributed at a level that warrants authorship and that contributions are consistently attributed among authors. Has each author made contributions in at least two areas in the authorship rubric? Did each author provide thoughtful, detailed feedback on the manuscript? Authors are encouraged to contact the HerbVar Steering Committee about any confusion or conflicts. -->

<!-- We encourage lead authors of working group papers to include as many co-authors as they can productively work with, to prioritize inviting HerbVar network members, and to prioritize inviting early-career scientists and scientists from under-represented groups or regions.  -->

<!-- ### Identifying & inviting potential co-authors of Working Group Papers -->

<!-- HerbVar provides a tool to help lead authors identify potential co-authors to invite to assist with working group papers. All Site PI’s are asked if they would like to be included in a database of individuals interested in co-authorship on small-group papers. The database lists name, career stage, institution and location, areas of expertise and/or topics of particular interest, number of HerbVar papers or manuscripts this person is an author on, what HerbVar datasets they have contributed to, and a link to their website or google scholar page or researchgate page.  -->

<!-- Note that for any of the approaches listed below, authorship requires at least two types of contribution to a paper; see Qualifying for Authorship. **The approaches for inviting co-authors listed below are on a continuum from least to most inclusive.** -->

<!-- 1. **Traditional**. The lead author invites known individuals with value for the particular paper. These individuals may not necessarily be HerbVar members. -->

<!-- 2. **Traditional Plus**. The lead author invites known individuals with value for the particular paper, plus a few people chosen from the HerbVar database as a good match for this project. -->

<!-- 3. **Application-based**. The lead author invites all HerbVar site PI’s who have contributed data to be used in the project to apply to be one of some limited number of authors, and chooses applicants to create the best team. -->

<!-- 4. **Opt-in: Limited**. The lead author decides on a number of co-authors they feel they can manage, and offers their paper to all HerbVar site PI’s who have contributed data to be used in this project on an “opt-in” basis. Site PI’s can opt-in until the desired number of collaborators is reached (first-come first-served).  -->

<!-- 5. **Opt-in: Open**. The lead author offers their paper to all HerbVar site PI’s who have contributed data to this project on an opt-in basis. Any site PI who wants to participate is invited. If considering this approach, we suggest reading this paper about writing a massively multi-authored paper. -->

<!-- ### Instructions for the _Opt-in_ approaches -->

<!-- The following steps should be used to identify and invite authors for the Opt-in approaches. -->

<!-- 1. The lead author uses the HerbVar co-author database to identifies site PIs who have contributed data to be used in this project.  -->

<!-- 2. The lead author circulates the manuscript proposal to the appropriate site PIs by attaching it as an email to the HerbVar email list. The subject line of the email should include the phrase “OPT-IN PAPER.” This email should also include a deadline by which time co-authors should respond.  -->

<!-- Once individuals wishing to opt-in respond to the lead author, the lead author is responsible for working with all co-authors to organzie the process and timeline for completing the paper. -->

<!-- ### When to invite co-authors -->

<!-- The right time to share your working draft and solicit co-authors is different for each manuscript, but in general: -->

<!-- - Sharing early drafts or figures allows for more effective co-author contribution. This would mean inviting co-authors at a very early stage. -->

<!-- - Circulating almost-complete manuscripts does not allow the opportunity for meaningful contribution from co-authors, and is discouraged. -->

<!-- ### Who should accept invitations to be a co-author? -->

<!-- Authorship must be earned through a substantial contribution. For co-authorship, each individual must contribute in *at least two ways* listed in the rubric below, including contribution to the writing process. Traditionally, project initiation and framing, data analysis and interpretation, and manuscript preparation are all authorship-worthy contributions, and remain so for HerbVar manuscripts. However, HerbVar collaborators have also agreed that contribution of data being used in a paper can be one factor qualifying a site PI for co-authorship, as long as the collaborator makes additional contributions to the particular manuscript, including data analysis, writing, or editing. HerbVar manuscripts will be accompanied by a supplemental table indicating authorship contributions. These guidelines apply equally to manuscripts led by graduate students. -->


<!-- | Rubric item | Example contributions counting towards authorship | -->
<!-- |----------|---------| -->
<!-- | Developed and framed research question(s) | Originated idea for current analysis of HerbVar data; contributed significantly to framing the ideas in this analysis at early stage of manuscript | -->
<!-- | Analyzed data | Generated models (conceptual, statistical and/or mathematical), figures, tables, maps, etc.; generated a Network-scale dataset being used in this manuscript’s analysis | -->
<!-- | Contributed to data analyses | Provided comments, suggestions, and code for data analysis | -->
<!-- | Wrote the paper | Wrote the majority of at least one of the sections of the paper | -->
<!-- | Contributed to paper writing | Provided new text, help with organization framing, and provided citations linking to new literature areas | -->
<!-- | Site PI | Coordinated data collection, proofing, and submission of data for at least one site used in this manuscript | -->
<!-- | Network level coordinators | Contributed substantially to network level activities such as management of network data, recruiting and assisting new sites, finding funding for network level management activities | -->

## Authorship Disputes

The steering committee works to ensure communication across projects to avoid overlap of manuscripts, and provides guidance on procedures and guidelines. Disputes over authorship and manuscripts should be brought to the Steering Committee (@sec-structure) for resolution.

## Manuscript Preparation

Please refer to @sec-workflow for details on the HerbVar Research Workflow and guide to preparing reproducible manuscripts. @sec-publications includes required information to include manuscripts, such as citations of Herbvar datasets and acknowledgement of NSF support.





