---
author: HerbVar Manual Authorship Team
title-block-style: plain
date: 11/01/2024
date-modified: last-modified
---
# Proposing New Data Collection {#sec-new_data_collection}

HerbVar network members are welcome to propose new add-on data collection efforts by sending a proposal to the Steering Committee. The Steering Committee will review proposals to ensure the network is focusing its efforts on the most important data collection objectives with the highest probability of success. 

## Species & Site Priorities {#sec-species_site}

Based on Phase 1 of data collection, we ask that you prioritize the following three objectives when proposing species for Phase 2 of data collection: 

### Objective 1: Focal species across gradients

**Goal: **Sample our three focal species -- _Taraxacum officinale_, _Plantago major_, and _Plantago lanceolata_ -- across broad geographic and/or environmental gradients.

**Justification:** Sampling within these three species will increase the depth of our understanding of the effects of particular abiotic gradients (e.g., elevation, precipitation, temperature, etc.) as drivers of variability in herbivory pressure within plant species. Each species is standardized within itself so studies of herbivory across a range of contexts allows for strong inference on the effects of those contexts.

### Objective 2: Novel species & contexts within focal families

**Goal: **Sample species from novel clades or with atypical growth forms within our five focal families -- Apocynaceae, Asteraceae, Fabaceae, Rubiaceae, and Solanaceae. Surveys of plant species that were included in Phase 1 are also welcomed but should prioritize novel regions, habitats, or environmental contexts.

**Justification:** Increased resolution within our five focal families allows for testing of drivers of herbivory variability in a phylogenetically-explicit framework. Understanding the impact of evolutionary differences within these families on the distribution of damage will be crucial in teasing apart macroevolutionary patterns.

### Objective 3: Damage to Reproductive Tissues

**Goal: **Survey damage to the fruits, flowers, and seeds of any species.

**Justification:** Damage to reproductive structures has–arguably–the most direct impact on fitness so an understanding of the drivers of variation in herbivory damage to reproductive tissues is crucial for understanding population-level or fecundity-related consequences of herbivory variation.



## Responsibilities of Add-on Project Leaders

**_Leaders of add-on projects must commit to:_**

- Creating the data-collection protocol with input from the Steering Committee.
- Recruiting site PIs to collect sufficient data for at least one publication.
- Leading the writing of at least one paper using their add-on project data.
- Including all site PIs who contribute substantially to the project as co-authors on at least one paper using project data. In most cases, a substantial contribution would be at least three surveys, although if other data collection is required (e.g., plant traits, herbivore counts, etc.), then “substantial” will be defined by the project leaders. All individuals who contribute data must have their efforts recognized with authorship, assuming that they also contribute to one additional aspect of authorship (see Authorship guidelines). 

## Proposal and Approval of New Add-on Projects

The steps to proposing a new add-on project are as follows: 

1. Review the current add-on projects and proposals for add-on projects to determine whether your idea is already being addressed. If not, proceed to step 2. 

2. Email a proposal to a Steering Committee member (contact information in @sec-structure). The proposal should have: 

     i. Working title
     ii. Current authors: including lead, co-leads, and additional authors. 
     iii. Abstract (~200 words) describing the knowledge gap, why it is important, and briefly describing the data to be collected to fill that knowledge gap and the protocol for collecting those data
     iv. Data: What data from the HV database will be used (e.g., Phase I, Phase II, all, etc.)
       - Response variables
       - Predictor variables
     v. Authorship model: We strongly recommend following the HerbVar core data authorship model, although many working groups may follow a different author model. Please see the authorship process here.
     vi. Timeline
       -	Data processing
       -	Analyses
       -	Writing
       -	Submission

The Steering Committee will review the proposal, ensuring there is no overlap with an ongoing data collection effort, and provide feedback. You will work with the Steering Committee to incorporate their feedback. If the proposal is approved, move to the next step.

3. Post your proposal for network members to read and email the network with “HerbVar add-on data project” in the subject line. Use some mechanism (return email, google form, etc.) to find out how many people want to opt-in to this project by contributing at least three surveys. 

4. If you have enough people opting-in to make the project viable, inform the Steering Committee and the project will be moved to “in-progress” on the HerbVar website. Depending on the complexity of your data, the Steering Committee or you will update our data structures to receive the new data.

5. Create and post your protocol, with Steering Committee input.

6. Send another email to the people opting in to your project telling them to start data collection.

## Evaluating Progress & Participation  {#sec-project-review}
<!-- # Review of HerbVar Projects and Participants -->

The HerbVar Steering Committee will review ongoing HerbVar projects, working groups and site PI’s periodically. Site PI’s whose behavior does not align with HerbVar guidelines (e.g., not reporting data errors, not treating collaborators with respect) will be asked to leave the project. Working Group leaders will be responsible for sharing their progress (e.g., manuscript drafts, results, data, code) with the Steering Committee when requested. If working groups do not make progress on their project within the first 6 months after a manuscript is proposed, or if they do not submit a manuscript within 2 years after proposal, the Steering Committee may suggest that the working group change its approach, or open the project to others who are interested in carrying it forward.

