---
author: Site PIs
title-block-style: plain
date: 11/01/2024
date-modified: last-modified
---

# Guidelines for Participation as a Site PI {#sec-site_pi}

The HerbVar Site PI is one of the most important roles in the network. Site PIs establish research sites, collect and submit data to ongoing sampling objectives, and assist with analyses and manuscript editing. **Site PIs must adhere to the following guidelines:**

- Be professionally-trained researchers with expertise in plant-herbivore interactions.
- Be inclusive, collegial, and collaborative in their interactions with other members of HerbVar.
- Have or obtain supplies necessary for conducting their own surveys. As a distributed network, HerbVar does not have funding for data collection.
- Contribute data gathered using a standard HerbVar protocol or a modified protocol approved by the Steering Committee (see @sec-primary).
- Contribute species-level data on each species they survey (i.e., species-level traits), as requested by the Steering Committee.
- Recognize the contributions of all individuals involved in collecting HerbVar data, even if that individual’s participation does not satisfy the criteria for authorship (see @sec-authorship_process). 
- Site PI’s should provide names, positions, and institutional affiliations of individuals who substantially contribute to data collection with them (“additional participants” columns in 'HerbVar Coordination' and 'Completed Surveys' documents). These additional participants will be recognized via the HerbVar website and via a link in the acknowledgments of HerbVar publications; we also encourage Site PIs to recognize local participation".
- Follow the HerbVar data sharing and usage agreement: HerbVar-DataSharingContract-D5.docx
- Ensure that your data are high quality. Check your data for errors before submitting them, and inform us immediately of any errors that you discover after submission. We identify and fix data errors to the extent possible as part of our data wrangling process. We understand that some errors are a normal part of data collection, but datasets that have an unreasonable number of errors will be rejected and not count towards authorship. We will not count errors against you if you contact us about them. Some  mistakes are expected; the most important thing is for Site PI’s to be alert for errors and to communicate openly about them when they happen. 


## Site PIs and authorship on HerbVar papers

### Authorship on “Core HerbVar Papers”

The HerbVar Network launched with a Steering Committee commitment to produce two papers using the core HerbVar data. Site PIs earn co-authorship on these papers by providing at least 3 surveys (though more are always welcome) to the core dataset. 

### Authorship on “add-on project” Papers

The Steering Committee has so far launched three add-on projects ("Focal Species", "Focal Families", "Reproductive Damage"); proposals for additional add-on projects are welcome (@sec-new_data_collection). Site PIs earn co-authorship on one paper from each add-on project by contributing at least three surveys (or equivalent) that advance that project, in addition to the minimum three surveys required for Site PI status and authorship on the core HerbVar papers. 

### Standards for Authorship and the HerbVar Authorship Process  

Authorship on papers arising from HerbVar data will be earned through significant contribution to the scientific process. Final authorship assignment is the responsibility of the lead author of the manuscript (where the lead author is the project leader approved by the Steering Committee). We strongly favor being inclusive in authorship. The detailed authorship guidelines can be found here. Site PIs who contribute to sampling objectives will earn authorship on the core paper that arises from that sampling effort. For more details on criteria for authorship see @sec-authorship_process.


