---
author: Nick Lyon
title-block-style: plain
date: 11/01/2024
date-modified: last-modified
---

# Google Drive Structure

This project has a lot of files coming and going so this is a brief description of all of those folders.

## Phase I Data Wrangling

-   HerbVar Phase I Data

-   All Uploads

-   All of the phase 1 raw data (and we’ve since moved to phase 2 so there should not be any more new data)

-   Phase I

-   Herbivore Data

-   herbivoreData (from the eponymous Excel sheet) raw, tidied at plant-level (one row per plant) and tidied at survey level (one row per survey) 

- Raw is the herbivore columns sliced off of the plantData sheet as part of the main wrangling script 

- Phase I - Primary Productivity 

- Primary productivity metadata to go along with phase 1 data 

- Phase I - Reproductive Data 

- Raw reproductive data columns sliced off of the plantData sheet as part of the main wrangling script 

- Phase I - Richness Data 

- Extracted native/invasive species richness from Ellis et al. 2012 

- Phase I - siteData - Tidied version of siteData (from eponymous Excel sheet) 

- Phase I - Survey Indices - Attempt (later abandoned) to split off just the site and plant-identifying information without any of the “actual” data. This would allow wide sharing of location information to enable all interested HerbVar members to harvest publicly-available metadata 

- Phase I Data - Wrangled 

- The “abiotic” (i.e., climatic) data for each site’s lat/long coordinates 
- The tidied plant-level data (one row per plant) for all phase 1 data 
- The tidied survey-level data (one row per survey) for all phase 1 data 
- HerbVar Foliage Index.xlsx - Index describing whether each species (from each PI) is deciduous, evergreen, or annual (this information was integrated into the phase 2 data submission portal so no equivalent Google Sheet will exist for phase 2 

## Phase II Data Wrangling 

- \_Data Submitted Via Email - I need to put it through the App - This is a clearinghouse for all raw phase 2 data that users send via email rather than using the submission portal. While discouraged, we don’t want to completely block data in such instances. So, once you receive data via email, drop it into this folder until you have the time to run it through the app (the handful of times this has occurred the data went through the portal fine, users just got frustrated from unrelated things) 

- App Uploads - Phase 2 - Raw data submitted via the portal arrive here 

## Phase II Completed Surveys Versions 
- All phase 2 wrangling scripts copy the completed surveys file with a time stamp to this folder for posterity. I can think of no direct utility of these backups but it doesn’t hurt to save them -

## Phase II Metadata 
- Rather than have separate folders for each metadata type (as was the case in phase 1) I have created this folder to contain them. Only abiotic (i.e., climatic) data have been retrieved so far but all should be placed here to keep the Drive folder hierarchy clean

## Phase II Raw Data 
- All data submitted through the submission portal should be manually moved from the “App Uploads - Phase 2” folder to here. The wrangling scripts will prompt you to do this if you do not before running them. 

## Phase II Wrangled Data - … 

- Each sheet of the Excel file has its own version of the above folder where the ellipses (...) is replaced by that sheet’s name. Where applicable (e.g., plantData, reproData, herbivoreData) there are survey-level (i.e., one row per survey) versions of the data 

## Miscellaneous Other Files 

_Note: this heading is not a folder name but refers to the random other files in the Drive._

- This manual is unfiled in the Drive! 
- The Data Management Plan (DMP) in graphical form 
- Tutorials for one-off tasks you may need to explain to others
