---
author: HerbVar Manual Authorship Team
title-block-style: plain
date: 11/01/2024
date-modified: last-modified
---

# Potential Collaborators

Potential collaborators typically get email either Will or the HerbVar Admin gmail address. If they contact will, he replies thanking them for their interest and forwards the email to you for follow-up. **These are the steps for handling new expressions of interest in collaborating:**     

1. Reply with the first email template (of 2) for prospective new members. Be sure to cc Will.

2. They respond and say:

a) they’re not interested/have issues with the expectations. 

  - Send them over to Will and stay on top of the email chain between them so you can know how he handled it. *This hasn’t happened, but in theory it could.*

b) They say that sounds fine and they’re still interested:

  i. Add them to the Collaborator Contact Information file

  ii. Add them as a “Contributor” to the HerbVar Shared Drive

  iii. Respond with the second email template (of 2)

It is important you send the email after doing the steps i and ii because the email template includes links that assumes (1) you have entered preliminary information into the collaborator contact info file and (2) they have access to everything in the HerbVar Shared Drive.

Note also that the second email template contains an onboarding document that you may need to update going forward as onboarding needs evolve.
