---
title: "Data-Sharing & Usage Agreement"
date-modified: last-modified
---


## Data-Sharing & Usage Agreement
## _Herbivory Variability Network_

---

The Herbivory Variability Network is a global network of scientists united in their aim to understand the role of variability in plant-herbivore interactions.

Collaboratively gathered datasets are increasingly valuable to scientific advancement, particularly for hypotheses that can only be tested with data across a wide geographic area. It is vital however that the products of such collaborations explicitly respect the contributions of the teams and individuals responsible for the collection of the data and development of protocols.

Note that data collected by Network members that has been published in a public repository already is not subject to this agreement and can be used freely, with appropriate citation. This agreement refers exclusively to unpublished data (including raw versions of published data).

---

**_Data Sharing Contract Conditions_**

----

1. The data sharer releases ownership of the data that they contribute to the HerbVar Network and allows the Network to use the data with appropriate credit given to the data sharer for scientific purposes (e.g., manuscripts, grant applications, etc.). Network members are credited as [here](https://herbvar.org/CollaboratorDirectory.html) and specific co-authorship guidelines for manuscripts produced from Network data are defined [here.](https://herbvar-network.github.io/herbvar_manual/introduction/Network_Structure.html)

2. The data sharer will not publish any findings or conclusions derived from analysis of shared Network data without a written collaboration agreement from the HerbVar Steering Committee (members [here](https://herbvar-network.github.io/herbvar_manual/introduction/Network_Structure.html)). Members are, however, entitled to publish their own personal datasets that they contribute.

3. The data sharer will not distribute, copy, or otherwise make available the shared data (either a subset or in full) to a third party without prior permission from the HerbVar Steering Committee. However, data may be shared with students for educational purposes with notification to the Steering Committee (such notification will be useful for grant annual reports and impact statements). Inappropriate distribution of data includes but is not limited to:

    a.	“Committing” the data to a version-controlled repository (e.g., git, SVN, etc.) that may be made public in future (thus making the data publicly available)
    b.	Placing the data files in a digital folder with un- or semi-restricted access
    c.	Sharing physical copies of the data with non-Network members (aside from the teaching exception detailed above)

4.	If a data sharer wishes to use shared Network data for a manuscript or grant application, the data sharer will provide a written Project Proposal to the HerbVar Network Steering Committee detailing plans for use of the data and any likely products. Changes to the proposed plan need to be approved by the Steering Committee.

IN WITNESS WHEREOF, the Data Sharer has hereunto executed this Data Sharing Agreement as of the date below written.


Printed Name:_________________

Signature:____________________

Date:_________________________

